### ISSUE TITLE
сборка части ui компонентов

### ISSUE THREAD

**Issue by effektivnayarabota1** [atls/team-management#11]
### С чем связан запрос на фичу?

поделили компоненты

### Расскажите как вы это себе видите

- [x] - Badge
- [x] - Switch
- [x] - Input
- [x] - Modal
- [x] - Dropdown

### Definition of done (критерий готовности)

ui слой собран, готовы компоненты

**Comment by effektivnayarabota1** [comment]
@Nelfimov не понимаю как решить ошибку типов на внешних пакетах
ветку актуализировал 

```
➤ YN0000: ┌ Format
➤ YN0000: └ Completed in 1s 244ms
➤ YN0000: Done in 1s 247ms
➤ YN0000: ┌ Typecheck
➤ YN0000: │ .yarn/__virtual__/@atls-ui-parts-input-virtual-93844aacd4/0/cache/@atls-ui-parts-input-npm-0.1.1-e57d4e695f-000f82aad0.zip/node_modules/@atls-ui-parts/input/dist/input/r
➤ YN0000: │ aw-input.component.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Cannot find type definition file for 'react'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ .yarn/__virtual__/@atls-ui-parts-switch-virtual-24fd0c36a9/0/cache/@atls-ui-parts-switch-npm-0.1.1-8284bcc81f-af1c1b0781.zip/node_modules/@atls-ui-parts/switch/dist/hand
➤ YN0000: │ le/handle.component.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Cannot find type definition file for 'react'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ .yarn/__virtual__/@atls-ui-parts-switch-virtual-24fd0c36a9/0/cache/@atls-ui-parts-switch-npm-0.1.1-8284bcc81f-af1c1b0781.zip/node_modules/@atls-ui-parts/switch/dist/hand
➤ YN0000: │ le/handle.element.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Cannot find type definition file for 'react'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: └ Completed in 7s 977ms
➤ YN0000: Failed with errors in 7s 977ms
➤ YN0000: ┌ Lint
➤ YN0000: └ Completed in 3s 559ms
➤ YN0000: Done in 3s 559ms

```

**Comment by TorinAsakura** [comment]
> @Nelfimov не понимаю как решить ошибку типов на внешних пакетах ветку актуализировал
> 
> ```
> ➤ YN0000: ┌ Format
> ➤ YN0000: └ Completed in 1s 244ms
> ➤ YN0000: Done in 1s 247ms
> ➤ YN0000: ┌ Typecheck
> ➤ YN0000: │ .yarn/__virtual__/@atls-ui-parts-input-virtual-93844aacd4/0/cache/@atls-ui-parts-input-npm-0.1.1-e57d4e695f-000f82aad0.zip/node_modules/@atls-ui-parts/input/dist/input/r
> ➤ YN0000: │ aw-input.component.d.ts
> ➤ YN0000: │ 
> ➤ YN0000: │   Error: Cannot find type definition file for 'react'.
> ➤ YN0000: │ 
> ➤ YN0000: │ 
> ➤ YN0000: │ .yarn/__virtual__/@atls-ui-parts-switch-virtual-24fd0c36a9/0/cache/@atls-ui-parts-switch-npm-0.1.1-8284bcc81f-af1c1b0781.zip/node_modules/@atls-ui-parts/switch/dist/hand
> ➤ YN0000: │ le/handle.component.d.ts
> ➤ YN0000: │ 
> ➤ YN0000: │   Error: Cannot find type definition file for 'react'.
> ➤ YN0000: │ 
> ➤ YN0000: │ 
> ➤ YN0000: │ .yarn/__virtual__/@atls-ui-parts-switch-virtual-24fd0c36a9/0/cache/@atls-ui-parts-switch-npm-0.1.1-8284bcc81f-af1c1b0781.zip/node_modules/@atls-ui-parts/switch/dist/hand
> ➤ YN0000: │ le/handle.element.d.ts
> ➤ YN0000: │ 
> ➤ YN0000: │   Error: Cannot find type definition file for 'react'.
> ➤ YN0000: │ 
> ➤ YN0000: │ 
> ➤ YN0000: └ Completed in 7s 977ms
> ➤ YN0000: Failed with errors in 7s 977ms
> ➤ YN0000: ┌ Lint
> ➤ YN0000: └ Completed in 3s 559ms
> ➤ YN0000: Done in 3s 559ms
> ```

также как и в остальных пакетах - через packageExtenstion

**Comment by effektivnayarabota1** [comment]
# _@Nelfimov_ Cтоит ли заниматься вот этими исключениями?

Например, версия [`dropdown`](https://github.com/atls/team-management/blob/feat/ui-components_pt%233/ui/dropdown/package.json) у меня совпадает с версией в консоли, но предупреждение все-равно возвращается.

`@emotion/react is listed by your project with version 11.11.4, which doesn't satisfy what @ui/dropdown (p85ece) and other dependencies request (11.11.3).`

---

```
➤ YN0060: │ @emotion/react is listed by your project with version 11.11.4, which doesn't satisfy what @ui/dropdown (p85ece) and other dependencies request (11.11.3).
➤ YN0060: │ @emotion/styled is listed by your project with version 11.11.5, which doesn't satisfy what @atls-ui-parts/layout (p437b8) and other dependencies request (11.11.0).
➤ YN0060: │ framer-motion is listed by your project with version 10.16.1, which doesn't satisfy what @atls-ui-parts/condition (p16aaf) requests (10.15.2).
➤ YN0060: │ react is listed by your project with version 18.3.1, which doesn't satisfy what @ui/dropdown (paf38f) and other dependencies request (18.2.0).
➤ YN0060: │ react-dom is listed by your project with version 18.3.1, which doesn't satisfy what @ui/dropdown (p9597b) and other dependencies request (18.2.0).
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
```

**Comment by Nelfimov** [comment]
Это просто предупреждения. Можно игнорировать а можно заняться перфекционизмом. Делается так:
1. `yarn upgrade-interactive`
2. апдейт всех `@atls...` пакетов
3. отлавливание предупреждений - у тебя в основном это будут понижения версий

**Comment by effektivnayarabota1** [comment]
# @Nelfimov в чем может быть причина? пытаюсь иконки собрать

```
[operator@archlinux icons]$ yarn build
Internal Error: spawn ETXTBSY
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at idr (/home/operator/work/07_atls_team-management/.yarn/releases/yarn-remote.cjs:9:57252)
    at mee.implementation (/home/operator/work/07_atls_team-management/.yarn/releases/yarn-remote.cjs:164:2151)
    at mee.exec (/home/operator/work/07_atls_team-management/.yarn/releases/yarn-remote.cjs:167:1706)
    at mee.run (/home/operator/work/07_atls_team-management/.yarn/releases/yarn-remote.cjs:167:1877)
    at VDr (/home/operator/work/07_atls_team-management/.yarn/releases/yarn-remote.cjs:173:6597)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BPi (/home/operator/work/07_atls_team-management/.yarn/releases/yarn-remote.cjs:175:16)
    at async f (/home/operator/work/07_atls_team-management/.yarn/releases/yarn-remote.cjs:175:147)
```

**Comment by Nelfimov** [comment]
Тебе ведь не надо билдить, а нужно запустить `generate-...`. Подгляди в том же drum-in

**Comment by effektivnayarabota1** [comment]
там просто этот скрипт упакован в `build`, я через `build` его и запускал как `готовое решение`
