### ISSUE TITLE
Сборка UI-компонентов 

### ISSUE THREAD

**Issue by bbulakh** [atls/team-management#14]
### С чем связан запрос на фичу?

Собрать базовый UI-слой для старта работы над проектом 

### Расскажите как вы это себе видите

Добавить компоненты:

- [x] - Divider
- [x] - Icon
- [x] - Checkbox
- [x] - Layout
- [x] - Progressbar
- [x] - Scroll

### Definition of done (критерий готовности)

Компоненты отображаются на странице, проект запускается без ошибок 

### Приложите материалы задачи

https://www.figma.com/file/2vNHefkDcMKAFSnw69RbMM/Team-management-system?type=design&node-id=0%3A1&mode=design&t=4ggv4h1MW40qD6J6-1

**Comment by bbulakh** [comment]
> @Nelfimov
> 
> Еще у меня есть компонент Checkbox, который я установил из Hyperion. Вот я пытаюсь вставить его в app/page, так же как с layout и пр. но он его не видит. Проблема в конфигах? Или надо делать вариант из ui-proto?
> 
> <img alt="image" width="793" src="https://private-user-images.githubusercontent.com/95144713/330069118-742cf285-b3d5-4e10-be4b-fd89d3ef7329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDkxNDcsIm5iZiI6MTcxNTYwODg0NywicGF0aCI6Ii85NTE0NDcxMy8zMzAwNjkxMTgtNzQyY2YyODUtYjNkNS00ZTEwLWJlNGItZmQ4OWQzZWY3MzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE0MDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwN2JiOTc0N2MxOTVjYjk4N2RhOGZmNWI0YWE2ZDk3MzU0ZWUxMWNjMDg0ZTE2NTlhZWViZDAxYTZjODQyOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0OeIZ33mVp88830s_94X3DaG6cFEDRGX6HpqJpoiZgc">


Касательно checkbox. Я его уже пушил, актуальная версия того, как я его подключаю есть:
https://github.com/atls/team-management/commits/feat/ui-components/

В экспортах есть Box и Check - оба не работают 
<img width="387" alt="image" src="https://github.com/atls/team-management/assets/95144713/58810eda-7e80-4749-82e2-d8c5caecd3ef">

**Comment by Nelfimov** [comment]
Посмотри внимательно что экспортируется там. Пример применения тех экспортов можешь увидеть в том же драмине: https://github.com/torin-asakura/drum-in/blob/master/ui/checkbox/package.json

В историях в том же пакете можешь увидеть как создается чекбокс который ты видишь тут

https://github.com/atls/hyperion/blob/master/ui-parts/checkbox/src/checkbox.stories.tsx
https://ui.atls.design/?path=/story/parts_components-checkbox--checkbox

Резюмируя - пакет `@atls-ui-parts/checkbox` экспортирует не готовые компоненты, а стили для подготовки чекбокса.

Ну и на будущее - ты можешь проверять что экспортирует пакет через автокомплит:

![image](https://github.com/atls/team-management/assets/44067768/eb5a3274-4109-4ae7-8463-7b2e171dad40)

**Comment by bbulakh** [comment]
@Nelfimov 

Касательно чекбокса - в итоге я делаю его из ```hyperion/ui-proto```.
Последний коммит: https://github.com/atls/team-management/commit/bfbf3b7c5f6932ec99b35d5a422424005ee58559
Я уже много чего почитал, посмотрел, поубирал лишних вещей (вроде). И сейчас он отображается на странице, но не работает. Выводит ошибку:
<img width="892" alt="image" src="https://github.com/atls/team-management/assets/95144713/324b1824-86d2-4e3a-a925-e36af253b833">

Можешь подсказать что я делаю не так?

**Comment by Nelfimov** [comment]
В энтрипоинте у тебя не передана функция чекбоксу в пропсах. Поэтому он не знает что делать.
