### ISSUE TITLE
Cборка фрагментов

### ISSUE THREAD

**Issue by effektivnayarabota1** [atls/team-management#18]
### С чем связан запрос на фичу?

Собираем компоненты во фрагменты

### Расскажите как вы это себе видите

Собрать фрагменты

### Definition of done (критерий готовности)

Все фрагменты готовы

### Приложите пример реализаций

https://www.figma.com/design/2vNHefkDcMKAFSnw69RbMM/Team-management-system

### Приложите материалы задачи
https://github.com/torin-asakura/drum-in/tree/master/landing/fragments

_No response_

**Comment by effektivnayarabota1** [comment]
# 1. страница регистрации
- [ ] сетка страницы регистрации
![image](https://github.com/atls/team-management/assets/70315473/c788d8da-281b-4bc1-b824-3b63d989cc3a)
- [ ] логотип? (расширить компонент?)
![image](https://github.com/atls/team-management/assets/70315473/f70e32b8-1491-4882-b52e-7d5cf8efc279)
# 2. homescreen
- [ ]  Заголовок + кнопка 
![image](https://github.com/atls/team-management/assets/70315473/71aa5720-5580-4487-bab0-dd146f89c7a2)
- [ ] grid
- [ ] каточки
- [ ] grid - карточек
- [ ] switch + notification
- [ ] модалка со скроллом (в нотификациях)
- [ ] модалка выбора оргинизации
- [ ] фрагмент организации внутри модалки (пред.пункт) (она разворачивается (может быть переместить в компоненты))
- [ ] добавление участника команды
# 3. организации
- [ ] сетка карточек
- [ ] карточка организации
- [ ] модалка оранизации
- [ ] бейдж? карточка ? (может быть готов компонент)
- [ ] мини бейдж (кожет быть готов компонент)
- [ ] модалка сотрудников
- [ ] элемент списка модалки (пред.пункт)

**Comment by effektivnayarabota1** [comment]
@bbulakh @effektivnayarabota1 @ssagg

### что решили:
1. отпочковываемся от ветки `feat/fragments` (@bbulakh создал) - в конце верстки всех фрагментов, _одним ПР замержимся в мастер_
2. цепляем фрагмент из списка в этом ишью **по одной штуке**, **подписывай юсернейм** у фрагмента который взял
3. по завершении фрагмента, создаем мерж в `feat/fragments`
4. если вносишь правки в компонент, сообщи всем, чтобы мы одновременно не правили один и тот же компонент.
5. правки по компонентам мерджим в  `feat/fragments`

**Comment by effektivnayarabota1** [comment]
@Nelfimov 
1. во фрагментах тоже задействуем тему по максимому? паддинги не числами ввожу, а через тему? **Через хук???** Или можно числами?
`<Box flexDirection='column' padding={'theme.spaces.micro'}>`
2. не нашел у `Box` пропс `gap`, вот так будет норм? 
`<Box flexDirection='column' style={{ gap: '24px' }}>`

**Comment by Nelfimov** [comment]
1. Да
2. Надо расширять пропсы. Если напомнишь - скину пример на выходных

**Comment by effektivnayarabota1** [comment]
> 2\. Надо расширять пропсы. Если напомнишь - скину пример на выходных

@Nelfimov посмотри пожалуйста пример

**Comment by effektivnayarabota1** [comment]
@bbulakh @ssagg я `Box` поправлю, в нашу ветку внесу обновления.

я в пятницу в эту ветку закидывал еще коммиты.мы из `radii` удалили все `f`, а некоторые компоненты требуют. 
строчные правки по компонентам я на ходу забрасываю, надеюсь путаницы не будет.
**перед мержем обновляйте ветку**

**Comment by Nelfimov** [comment]
> отпочковываемся от ветки feat/fragments (@bbulakh создал) - в конце верстки всех фрагментов, одним ПР замержимся в мастер

Будьте внимательны - от какой ветки отпочковались, туда ПР и должен быть. Иначе у вас будут разные истории коммитов. В вашем случае последовательность мержей должна быть такая:

- `ваша ветка` -> `feat/fragments` -> master

**Comment by effektivnayarabota1** [comment]
@Nelfimov 
У реакта есть такой функционал, чтобы зафиксировать определенные пропсы на `children`?
[`switch`](https://github.com/atls/team-management/blob/efa75c4bd1c5ba0e783ce879b4186334b0ff1aca/ui/switch/src/icon-switch/icon-switch.component.tsx) предпологает вложение иконок, и эти иконки нужно подгонять под размер и менять фон на прозрачный. Я делаю это на уровне `fragments` для каждой из четырех иконок, было бы удобнее зашить это в компонент

**Comment by Nelfimov** [comment]
Только если ты ограничишь их боксом или лэйаутом - в остальном `children` для компонента - любой набор компонентов со своими пропсами.

**Comment by ssagg** [comment]
@effektivnayarabota1 @bbulakh а чекбокс рабочий? что-то у меня галкане проставляется.

**Comment by effektivnayarabota1** [comment]
@Nelfimov 
1. валидацию на этом этапе делаем? какаято библиотека есть для этого?
2. как лучше активацию кнопки снизу сделать? мне приходит идея только вынести `state` и у каждого элемента в **`хендлере`** `проветка` => `setState`
![image](https://github.com/atls/team-management/assets/70315473/2f1f095e-9ed6-4b89-a9ff-84bf8561001a)

**Comment by ssagg** [comment]
@effektivnayarabota1 привет. ты в с organization card испоьзуешь styled обертки. хотя есть компонет Card. В который надо все помещать. Он универсальный.

**Comment by ssagg** [comment]
@effektivnayarabota1 добавил пропс грида в Layout в последнем ПР

**Comment by effektivnayarabota1** [comment]
> @effektivnayarabota1 добавил пропс грида в Layout в последнем ПР
я вот такой вчера компонент в `layout` добавил, сейчас запушу:
я по-другому немного делаю, `размеры контейнера` задаю через `размеры колонок` родительской `grid`, а ребенок на 100% по всем осям.
как ты думаешь, все-таки как делать лучше и почему?)
![image](https://github.com/atls/team-management/assets/70315473/c7deae63-73a5-4914-b862-86f1f8f933d0)

**Comment by effektivnayarabota1** [comment]
> @effektivnayarabota1 добавил пропс грида в Layout в последнем ПР

а я вот не могу понять смысл универсальных компонентов. он же просто пропсы ловит и все. он бы зафиксировал общие для всех `Card` стили, чтобы мы не писали каждый раз одно и тоже. а так все-равно что с `card`, что через `box`, все прописываю.

**Comment by effektivnayarabota1** [comment]
> > @effektivnayarabota1 добавил пропс грида в Layout в последнем ПР
> > я вот такой вчера компонент в `layout` добавил, сейчас запушу:
> > я по-другому немного делаю, `размеры контейнера` задаю через `размеры колонок` родительской `grid`, а ребенок на 100% по всем осям.
> > как ты думаешь, все-таки как делать лучше и почему?)
> > ![image](https://private-user-images.githubusercontent.com/70315473/335459087-c7deae63-73a5-4914-b862-86f1f8f933d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzUzMzcsIm5iZiI6MTcxNzEzNTAzNywicGF0aCI6Ii83MDMxNTQ3My8zMzU0NTkwODctYzdkZWFlNjMtNzNhNS00OTE0LWI4NjItODZmMWY4ZjkzM2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA1NTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYWFjZjFjZTJmNzZhZTBkY2E5YzQwYzI0NWE1NmVjNmQ0NDZjMTI1ZDc2MDViMWFmNGExNTVmY2UwNjdiZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0q3C655vFK9-VNq791WDFWzUq6MErxn-EKHCUNSDZdI)

https://github.com/atls/team-management/blob/refactor/fragments_modals/ui/layout/src/grid/grid.component.tsx

**Comment by effektivnayarabota1** [comment]
@ssagg а вот такую штуку не делал случайно?
![image](https://github.com/atls/team-management/assets/70315473/5c7dd956-beac-4d33-b800-52085ae18a9a)

**Comment by ssagg** [comment]
> @ssagg а вот такую штуку не делал случайно? ![image](https://private-user-images.githubusercontent.com/70315473/335485140-5c7dd956-beac-4d33-b800-52085ae18a9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDEyNDYsIm5iZiI6MTcxNzE0MDk0NiwicGF0aCI6Ii83MDMxNTQ3My8zMzU0ODUxNDAtNWM3ZGQ5NTYtYmVhYy00ZDMzLWI4MDAtNTIwODVhZTE4YTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA3MzU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTkzYjM3ZTgxNTMzOTNiNzVmYjFiOTcwZDE4M2ZjNGIxYzI3OTdlMzIxYTllNDQyYjc0OTIzNjBmNDVhMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ESvVmY9KDxH-RY3bkjjEM5-ZviaD_EfQPgJJuUxdesc)

Почти полностю повторяет элемент из сайдбара. Сейчас запушу.

**Comment by ssagg** [comment]
@Nelfimov @effektivnayarabota1 я создал ПР в ветку fragments. Добавил бейдж. Или могу напрямую туда заливать?

**Comment by ssagg** [comment]
> > @effektivnayarabota1 добавил пропс грида в Layout в последнем ПР
> 
> а я вот не могу понять смысл универсальных компонентов. он же просто пропсы ловит и все. он бы зафиксировал общие для всех `Card` стили, чтобы мы не писали каждый раз одно и тоже. а так все-равно что с `card`, что через `box`, все прописывать придется.

Так-то можно вообще все на боксах написать) именно в данном случае Кард это больше семантика. т.к. карточки у нас сильно отличаются по дизайну и там ничего не зафиксируешь, разменры, радиусы, цвета, все разное. А в целом, ты же можешь переиспользовать компонент.

**Comment by effektivnayarabota1** [comment]
> > > @effektivnayarabota1 добавил пропс грида в Layout в последнем ПР
> > 
> > 
> > а я вот не могу понять смысл универсальных компонентов. он же просто пропсы ловит и все. он бы зафиксировал общие для всех `Card` стили, чтобы мы не писали каждый раз одно и тоже. а так все-равно что с `card`, что через `box`, все прописывать придется.
> 
> Так-то можно вообще все на боксах написать) именно в данном случае Кард это больше семантика. т.к. карточки у нас сильно отличаются по дизайну и там ничего не зафиксируешь, разменры, радиусы, цвета, все разное. А в целом, ты же можешь переиспользовать компонент.

да, имеет смысл.
может объеденим карточки по стилям? зафиксируем скругления и тень, например.

**Comment by effektivnayarabota1** [comment]
> @Nelfimov @effektivnayarabota1 я создал ПР в ветку fragments. Добавил бейдж. Или могу напрямую туда заливать?

бейдж уде в инпут добавил. там инпут сильно преебрал с этими бейджами, щас рефакторить буду и заливать, не используй пока нигде. сегодня закончу.

**Comment by effektivnayarabota1** [comment]
> > > @effektivnayarabota1 добавил пропс грида в Layout в последнем ПР
> > > я вот такой вчера компонент в `layout` добавил, сейчас запушу:
> > > я по-другому немного делаю, `размеры контейнера` задаю через `размеры колонок` родительской `grid`, а ребенок на 100% по всем осям.
> > > как ты думаешь, все-таки как делать лучше и почему?)
> > > ![image](https://private-user-images.githubusercontent.com/70315473/335459087-c7deae63-73a5-4914-b862-86f1f8f933d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzUwNzksIm5iZiI6MTcxNzEzNDc3OSwicGF0aCI6Ii83MDMxNTQ3My8zMzU0NTkwODctYzdkZWFlNjMtNzNhNS00OTE0LWI4NjItODZmMWY4ZjkzM2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA1NTI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYjFlNjU0MWU4OTVlMzFlOWVmM2YzMjk0OWJmMWU4YTM3ODkyMzIyMmJkMDdkOWU0MDZhMDljZGUwZDRiYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ljKZUZhvpV4R54EE1aNeS2tWEgq-357QoEcOAOcFoO4)
> 
> это к layout, box, row , column добвляется еще грид компонент получается. я просто добавил пропс грида в бокс. и бокс по дефолту флекс, а при необходимости - грид.

я колчиество колонок в пропс просто вынес, мне показалось что так удобно будет. не стоку вбивать а цисло просто

**Comment by effektivnayarabota1** [comment]
# @Nelfimov 🆘🆘🆘🆘🆘🆘⚠️⚠️⚠️⚠️⚠️⚠️☠️☠️☠️☠️☠️☠️
1. В компоненте [**input**](https://github.com/atls/team-management/blob/draft/ui/input/src/input.component.tsx
) много хуков для дочерних компонентов. я хочу это отрефакторить и разнести хуки к детям. не понимаю как это сделать, ведь хуки используют `стейт-переменные` друг-друга. объявлять `стейт-переменные` в родителе, импортировать `хук` через родителя и закидывать обратно детям, с `стейт-переменными (и функциями)`???
если не сложно, посмотри пожалуйста пример
2. [вот здесь](https://github.com/atls/team-management/issues/18#issuecomment-2135309195) так и не понял. нужно контекст создать у каждого компонента?
сейчас пришла идея вынести контекст в `utils`, это так делается?

**Comment by effektivnayarabota1** [comment]
@Nelfimov не понимаю, как быть с типами у контекста
```
➤ YN0000: │ .yarn/__virtual__/@ui-input-virtual-f459a9694d/1/ui/input/src/select-input/selected-item/selected-item.component.tsx:29:32
➤ YN0000: │ 
➤ YN0000: │   Error: Conversion of type 'null' to type 'Dispatch<any>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the 
➤ YN0000: │        expression to 'unknown' first.
➤ YN0000: │ 
➤ YN0000: │   27 |
➤ YN0000: │   28 |   const theme: any = useTheme()
➤ YN0000: │ > 29 |   const selectedItemsDispatch = useContext(SelectedItemsDispatchContext) as Dispatch<any>
➤ YN0000: │      |                                ^
➤ YN0000: │   30 |
➤ YN0000: │   31 |   function handleDeleteSelectedItem(e, itemData) {
➤ YN0000: │   32 |     selectedItemsDispatch({
```

```
➤ YN0000: │ .yarn/__virtual__/@ui-input-virtual-f459a9694d/1/ui/input/src/select-input/select-input.component.tsx:103:50
➤ YN0000: │ 
➤ YN0000: │   Error: Type 'Dispatch<null>' is not assignable to type 'null'.
➤ YN0000: │ 
➤ YN0000: │   101 |           <SelectedItemsDispatchContext.Provider value={selectedItemsDispatch}>
➤ YN0000: │   102 |             <InputValueContext.Provider value={inputValue}>
➤ YN0000: │ > 103 |               <InputValueDispatchContext.Provider value={inputValueDispatch as Dispatch<null>}>
➤ YN0000: │       |                                                  ^
➤ YN0000: │   104 |                 <InputBox
➤ YN0000: │   105 |                   {...props}
➤ YN0000: │   106 |                   {...triggerProps}
```

**Comment by Nelfimov** [comment]
а зачем ты его через `Dispatch` переопределяешь?

**Comment by effektivnayarabota1** [comment]
_@Nelfimov_
# 1. подскажи пожалуйста, как `TS` определяет типы для ипортируемого `JSON`?
локали поместил в `JSON`, на импорте ошибка типов.

### `JSON` приходит в таком виде:
```
app-1   | [Object: null prototype] [Module] {
app-1   |   'add-member-modal.header': [Getter],
app-1   |   'add-member-modal.invite': [Getter],
app-1   |   'add-member-modal_input.invalid-email': [Getter],
app-1   |   'add-member-to-organization-modal.header': [Getter],
app-1   |   'add-member-to-organization-modal_input.placeholder': [Getter],
app-1   |   'organization-card_member.one': [Getter],
app-1   |   'organization-card_member.many': [Getter],
app-1   |   default: [Getter]
app-1   | }
```
### Ошибка выгляди вот так:
```
➤ YN0000: │   Error: No overload matches this call.
➤ YN0000: │          Overload 1 of 2, '(props: PropsWithChildren<IntlConfig>): IntlProvider', gave the following error.
➤ YN0000: │            Type '{ default: { "add-member-modal.header": string; "add-member-modal.invite": string; "add-member-modal_input.invalid-email": string; 
➤ YN0000: │        "add-member-to-organization-modal.header": string; "add-member-to-organization-modal_input.placeholder": string; "organization-card_member.one": string; 
➤ YN0000: │        "organization-card_member.many": ...' is not assignable to type 'Record<string, string> | Record<string, MessageFormatElement[]> | undefined'.
➤ YN0000: │              Type '{ default: { "add-member-modal.header": string; "add-member-modal.invite": string; "add-member-modal_input.invalid-email": string; 
➤ YN0000: │        "add-member-to-organization-modal.header": string; "add-member-to-organization-modal_input.placeholder": string; "organization-card_member.one": string; 
➤ YN0000: │        "organization-card_member.many": ...' is not assignable to type 'Record<string, MessageFormatElement[]>'.
➤ YN0000: │                Index signature for type 'string' is missing in type '{ default: { "add-member-modal.header": string; "add-member-modal.invite": string; 
➤ YN0000: │        "add-member-modal_input.invalid-email": string; "add-member-to-organization-modal.header": string; "add-member-to-organization-modal_input.placeholder": string; 
➤ YN0000: │        "organization-card_member.one": string; "organization-card_member.many": ...'.
➤ YN0000: │          Overload 2 of 2, '(props: PropsWithChildren<IntlConfig>, context: any): IntlProvider', gave the following error.
➤ YN0000: │            Type '{ default: { "add-member-modal.header": string; "add-member-modal.invite": string; "add-member-modal_input.invalid-email": string; 
➤ YN0000: │        "add-member-to-organization-modal.header": string; "add-member-to-organization-modal_input.placeholder": string; "organization-card_member.one": string; 
➤ YN0000: │        "organization-card_member.many": ...' is not assignable to type 'Record<string, string> | Record<string, MessageFormatElement[]> | undefined'.
```

# 2. Ошибка типов пакета `react intl`
версия пакета взял из драм ина, апгрейднул до последней минорной, не помогло.
![image](https://github.com/atls/team-management/assets/70315473/96d12ad5-188e-46f8-89f0-17a13758eb94)
```
➤ YN0000: │   Error: Interface 'DateTimeFormat' incorrectly extends interface 'Omit<DateTimeFormat, "resolvedOptions">'.
➤ YN0000: │          The types returned by 'formatRangeToParts(...)' are incompatible between these types.
➤ YN0000: │            Type 'IntlDateTimeFormatPart[]' is not assignable to type 'DateTimeRangeFormatPart[]'.
➤ YN0000: │              Type 'IntlDateTimeFormatPart' is not assignable to type 'DateTimeRangeFormatPart'.
➤ YN0000: │                Types of property 'source' are incompatible.
➤ YN0000: │                  Type 'RangePatternType | undefined' is not assignable to type '"shared" | "startRange" | "endRange"'.
➤ YN0000: │                    Type 'undefined' is not assignable to type '"shared" | "startRange" | "endRange"'.
```
