### ISSUE TITLE
Создание энтрипоинта

### ISSUE THREAD

**Issue by Nelfimov** [atls/team-management#2]
### С чем связан запрос на фичу?

Для приложения нужно собрать энтрипоинт для дальнейшей разработки команды.

### Расскажите как вы это себе видите

- [x] собрать энтипоинт
- [x] убедиться что все зависимости есть
- [x] убедиться что запуск происходит

### Definition of done (критерий готовности)

Энтрипоинт создан, запускается без ошибок.

### Приложите пример реализаций

https://github.com/atls-lab/frontend/tree/master/app-router/entrypoints/renderer
https://github.com/torin-asakura/drum-in/tree/master/landing/entrypoints/renderer
https://github.com/torin-asakura/dream-team/tree/master/landing/entrypoints/renderer

### Приложите материалы задачи

https://www.figma.com/file/2vNHefkDcMKAFSnw69RbMM/Team-management-system?type=design&node-id=0-1&mode=design&t=Xbq1nSce06sKbif8-11

**Comment by bbulakh** [comment]
@Nelfimov 

Я делаю фикс энтрипоинта, чтобы пройти проверки. Сначала я переписал файлы в app на стрелочные функции и оставалась всего одна ошибка

`Error: Cannot find module 'scheduler/tracing' or its corresponding type declarations.`

Я еще раз сделал `yarn install`, `yarn lint` и в итоге выдаёт это:
(.pnp.cjs на месте, всё запускается. Пробовал чистить кэш, ставить зависимости заново, не помогло)

➤ YN0000: ┌ Lint
➤ YN0000: │ Cannot find module '/Users/b_bulakh/Documents/ATLS/team-management/app/entrypoints/renderer/.pnp.cjs'
➤ YN0000: │ Require stack:
➤ YN0000: │ - internal/preload
➤ YN0000: │ 
➤ YN0000: │ Module._resolveFilename                                                                               node:internal/modules/cjs/loader:1077:15
➤ YN0000: │ Module._load                                                                                           node:internal/modules/cjs/loader:922:27
➤ YN0000: │ internalRequire                                                                                        node:internal/modules/cjs/loader:174:19
➤ YN0000: │ Module._preloadModules                                                                                 node:internal/modules/cjs/loader:1433:5
➤ YN0000: │ loadPreloadModules                                                                                   node:internal/process/pre_execution:598:5
➤ YN0000: │ setupUserModules                                                                                     node:internal/process/pre_execution:117:3
➤ YN0000: │ MessagePort.<anonymous>                                                                                 node:internal/main/worker_thread:132:5
➤ YN0000: │ [nodejs.internal.kHybridDispatch]                                                                            node:internal/event_target:741:20
➤ YN0000: │ exports.emitMessage                                                                                node:internal/per_context/messageport:23:28
➤ YN0000: └ Completed

**Comment by Nelfimov** [comment]
`yarn lint` запускай из корня проекта

**Comment by bbulakh** [comment]
Понял, тогда осталась эта ошибка:

`.yarn/cache/@types-react-npm-18.2.48-3bda252d86-2e56ea6bd8.zip/node_modules/@types/react/index.d.ts`
`Error: Cannot find module 'scheduler/tracing' or its corresponding type declarations.`

Этот тип нужно указать в какой-то из package.json?

**Comment by Nelfimov** [comment]
актуализируй ветку, я посмотрю

**Comment by Nelfimov** [comment]
Забирай, пофиксил. Это внутренняя ошибка типов, ее можно решить только "подбором" версий.

**Comment by bbulakh** [comment]
@Nelfimov запросил повторное ревью
