### ISSUE TITLE
Cборка фрагментов - Card

### ISSUE THREAD

**Issue by ssagg** [atls/team-management#20]
### С чем связан запрос на фичу?

Собираем компоненты во фрагменты

### Расскажите как вы это себе видите

Собрать фрагменты

### Definition of done (критерий готовности)

фрагменты готовы

### Приложите пример реализаций

https://www.figma.com/design/2vNHefkDcMKAFSnw69RbMM/Team-management-system

### Приложите материалы задачи

https://github.com/torin-asakura/drum-in/tree/master/landing/fragments

**Comment by ssagg** [comment]
Собран фрагмент карточки. Работаю на д чекбоксами и скролом

**Comment by Nelfimov** [comment]
Почему меня поставил ответственным?
