### ISSUE TITLE
organizations page

### ISSUE THREAD

**Issue by effektivnayarabota1** [atls/team-management#23]
### С чем связан запрос на фичу?

работа по макету

### Расскажите как вы это себе видите

сборка страницы из готовых фрагметов, компонентов

### Definition of done (критерий готовности)

верстка соотвтетсвуеn макету. переключение темы

### Приложите пример реализаций

![image](https://github.com/atls/team-management/assets/70315473/b8a1ac82-0b53-42c1-83a4-ddb4e6e3dfa4)

### Приложите материалы задачи

https://www.figma.com/design/2vNHefkDcMKAFSnw69RbMM/Team-management-system?node-id=0-1&t=vXJyHoojNyOYUYeh-0

**Comment by effektivnayarabota1** [comment]
@Nelfimov 
скажи пожалуйста на каком уровне лучше делать запрос к БД - 
1. на уровне `page`, например, в хендлере при клике. Все необходимые пропсы пропидывать вниз
2. в самом компоенте, onMount. У родителя просить только айди

**Comment by Nelfimov** [comment]
Погоди с БД - сначала верстка, а потом - интеграция с бэком.

**Comment by ssagg** [comment]
@effektivnayarabota1 нам бы Sidebar, theme selector и title сделать в Layout. Тогда они не будут ререндериться при переходе по меню. а в чилдрен уже передавать контент @Nelfimov что скажешь?

**Comment by Nelfimov** [comment]
В плане оптимизации все верно.
