### ISSUE TITLE
apollo/client&graphql

### ISSUE THREAD

**Issue by effektivnayarabota1** [atls/team-management#29]
### С чем связан запрос на фичу?

Сервер

### Расскажите как вы это себе видите

В процессе

### Definition of done (критерий готовности)

В процессе

### Приложите материалы задачи

[creating oAuth app](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app)
[Authorizing OAuth apps](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps)

https://github.com/octokit/auth-oauth-user.js?tab=readme-ov-file#usage-with-octokit
![image](https://github.com/atls/team-management/assets/70315473/8f235aec-eeac-444c-9d7c-062333946b68)

**Comment by Nelfimov** [comment]
В дополнение для работы с GitHub - https://www.npmjs.com/package/octokit

**Comment by effektivnayarabota1** [comment]
@Nelfimov подскажи пожалуйста как graphQl сервер создать?
![image](https://github.com/atls/team-management/assets/70315473/f9d25b25-cf1a-47e1-9e8b-427a974ab0c7)

**Comment by Nelfimov** [comment]
А зачем тебе сервер? Твое основное взаимодействие - GitHub GraphQL

**Comment by effektivnayarabota1** [comment]
@Nelfimov 
1. не могу понять, как сделать авторизацию через `octokit`, сделал [`вот так`](https://github.com/atls/team-management/blob/feat/authorizaiton/app/entrypoints/renderer/src/app/api/github/route.ts)
сейчас сохраняемся в куки, без соли.

2. в текущем варианте есть `middleware`, который записывает в куки ключ с гитхаба, потом этот `response` передается в `api-route`, который делает `редикет домой`. я добавил `middleware`, потомучто не получилось записать куки в ендпоинте. вопрос лишь в том, возможно ли так сделать? (что-то мне подсказывает что можно)

2. знаю библиотеку [iron-session](https://github.com/vvo/iron-session), будем на неё переделывать или какоето похожее решение?

3. у гитхаб-приложения есть ключи, которые я хотел бы поместить в `.env` эти переменные компонент не видит, как я понял потому-что `'use client'`, как это можно исправить? или другой способ передавать ключи.

**Comment by Nelfimov** [comment]
> 1. не могу понять, как сделать авторизацию через `octokit`, сделал [`вот так`](https://github.com/atls/team-management/blob/feat/authorizaiton/app/entrypoints/renderer/src/app/api/github/route.ts)
>    сейчас сохраняемся в куки, без соли.

Грубыми мазками:
1. авторизоваться в GitHub
2. получить от них токен
3. этот токен использовать в `octokit`
4. хранить можешь в куках

> в текущем варианте есть middleware, который записывает в куки ключ с гитхаба, потом этот response передается в api-route, который делает редикет домой. я добавил middleware, потомучто не получилось записать куки в ендпоинте. вопрос лишь в том, возможно ли так сделать? (что-то мне подсказывает что можно)

ты ведь можешь программно записать куки. Зашли в приложение - регистрация/авторизация в github (можешь сделать тестовое личное приложение) - ловишь в ответ креды - сохраняешь в куках.

> знаю библиотеку [iron-session](https://github.com/vvo/iron-session), будем на неё переделывать или какоето похожее решение?

Пока не будем усложнять

> у гитхаб-приложения есть ключи, которые я хотел бы поместить в .env эти переменные компонент не видит, как я понял потому-что 'use client', как это можно исправить? или другой способ передавать ключи.

Нужен префикс `NEXT_PUBLIC` чтобы браузер видел env. Иначе они остаются на сервере.

**Comment by effektivnayarabota1** [comment]
> Грубыми мазками:
> 
> 1. авторизоваться в GitHub
> 2. получить от них токен
> 3. этот токен использовать в `octokit`
> 4. хранить можешь в куках

это готово. думал что через `октокит` можно и авторизацию сделать

**Comment by effektivnayarabota1** [comment]
@Nelfimov 
1. `octokit` у нас будет делать запросы на уровне `fragments`, не на уровне `pages`?
2. куда разместить объект авторизации (см скриншот)? Если он будет переиспользоваться по всему приложению, то в `globals/data` будет норм?
![image](https://github.com/atls/team-management/assets/70315473/6dacbb16-2f75-4b37-a749-93baeb23658d)

**Comment by Nelfimov** [comment]
> 1. `octokit` у нас будет делать запросы на уровне `fragments`, не на уровне `pages`?

По структуре кода - `fragments`.

А вот для того чтобы нам получать данные еще на сервере, чтобы не было "морганий" получения данных на клиенте - `pages`.

> 2. куда разместить объект авторизации (см скриншот)? Если он будет переиспользоваться по всему приложению, то в `globals/data` будет норм?

Да, можно. Надо еще понимать нужно ли тебе этот стейт использовать по приложению в разных кусках. Если да - то еще дополнительно делать `stores/user`

**Comment by effektivnayarabota1** [comment]
https://docs.github.com/en/graphql/reference/objects#user

**Comment by effektivnayarabota1** [comment]
https://github.com/octokit/authentication-strategies.js/?tab=readme-ov-file#oauth-app-authentication

**Comment by Nelfimov** [comment]
если ты это скидываешь себе на память, то лучше
- либо редактировать изначальную задачу и туда добавлять "Материалы"
- либо открывать дискуссии в репе и добавлять туда мысли и материалы

**Comment by effektivnayarabota1** [comment]
> * дискуссии

подскажи что такое дискусси

**Comment by ssagg** [comment]
@effektivnayarabota1 @Nelfimov  через octokit запросы в гит идут. мы можем этот пакет использовать и для запросов?
или надо через useQuery от apollo?
сделали тестовую организацию. на ней будем тренироваться.
` 
const dataOrg = await octokit.graphql(query{

    organization(login: "ssagg-test") {
      name
      teams(first: 100, after: null) {
        nodes {
          members {
            nodes {
              avatarUrl
              name
              email
              id
              organizations(first:100){
                nodes{
                  id
                  name
                  avatarUrl
                }
              }
            }
          }
          name
        }
      }
    }
  }) 
`
![Screenshot from 2024-06-21 13-54-56](https://github.com/atls/team-management/assets/104500533/e45a9a70-e8f1-48b6-be30-093d92938c43)

**Comment by Nelfimov** [comment]
Octokit без Apollo - норм. Только рассмотрите ещё graphql codegen для типизации запросов https://the-guild.dev/graphql/codegen

**Comment by Nelfimov** [comment]
`apollo` не нужен
