### ISSUE TITLE
страница организаций

### ISSUE THREAD

**Issue by effektivnayarabota1** [atls/team-management#35]
### С чем связан запрос на фичу?

получение данных для одной из 2х страниц; продолжаем работу над бэком

### Расскажите как вы это себе видите

- [x] получение списка организаций, в которых пользователь имеет права администратора
![image](https://github.com/atls/team-management/assets/70315473/e601986f-4f7a-4361-b628-321ab9f7c546)
  - [x] можно получать **список всех организаций** авторизированного пользователя, но если пользователь **не емеет прав** на добавление новых сотрудников, то делать кнопку `disabled`
- [x] добавление сотрудника в организацию (`модальное окно`)
![image](https://github.com/atls/team-management/assets/70315473/6681667c-9187-44a5-9409-fc72368d60b7)
  - [x] изменить компонент на `github-search-users-input`. функционал текущего компонена не состыковывается с необходимым
  - [x] откуда приходит список сотрудников _(общий список всех сотрудников)_?
  - [x] что такое команды организации _(см. скриншот)_?
![image](https://github.com/atls/team-management/assets/70315473/36518b8b-d8a4-4491-9984-bd57860ffbb5)
- [x] получение списка сорудников в оргиназации (`модальное окно`)
![image](https://github.com/atls/team-management/assets/70315473/2d5a6506-7401-49d0-a7a0-bb375703326e)
- [x] удаление сотрудника из организации (`кнопка в модальном окне^`)
  - не могу найти `graphql endpoint `
  - если не найду в итоге, можно использовать `rest`, он гарантированно есть
- [x] удаление только, если у `вьювера` есть права администратора
![image](https://github.com/atls/team-management/assets/70315473/0392a08f-1aca-46a3-b214-c9d767a84e6c)
- [x] выводить ошибки при запросах на клиент
    - [x] добавить компоненту `error-message` - `reducer`. 
- [x] попробовать вынести вывод ошибок на самый высокий уровень. (ui свойство в объекте ошики)
- [x] оповещать юсера об успешном выполнении запроса
    - [x] один вариант - `изменение стиля кнопки в модальном окне` (приглашение юсера)
    - [x] второй вариант - `тост нотификейшн синего цвета`. дизайн нарисовали. (при удалении юсера)
- [x] рефакторинт

### Definition of done (критерий готовности)

все готово

**Comment by ssagg** [comment]
@effektivnayarabota1 привет. Если тебе понадобятся запросы пользователей. 

вместо логина - название оганизации
query FindUsersInOrg {
  organization(login: "ssagg-test") {
    membersWithRole(first: 100, after: null) {
      nodes {
        name
        email
        avatarUrl
        id
      }
    }
  }
}


еще через команды можно. но, тольк если эти команды есть и пользователь в команде. Правда потом данные надо отфильтровать от дублей пользователей, если один пользователь в несколькиз командах.

query FindUsersInTeams {
  organization(login: "ssagg-test") {
    teams(first: 100, after: null) {
      nodes {
        members {
          nodes {
            avatarUrl
            name
            id
            organizations(first: 100) {
              nodes {
                id
                name
                avatarUrl
              }
            }
          }
        }
        name
      }
    }
  }
}

**Comment by effektivnayarabota1** [comment]
@ssagg ты же запрашиваешь данные по `ВСЕМ СОТРУДНИКАМ`, `ВСЕХ ОРГАНИЗЦИЙ`, в которых у `ВЬЮВЕРА` есть права на это?

@Nelfimov поиск, тот что на скриншоте, я делаю по `всем гитхабовским профилям`, верно (глобальный поиск)? Соответственно делаю на клиенте, в UI ограничиваю вывод на несколько штук
(если делать поиск исключительно по `УЧАСТНИКАМ НАШИХ ОРГАНИЗАЦИ`, то нового пользователя нужно будет добавлять в организацию вручную через `ГИТХАБ`)
![image](https://github.com/atls/team-management/assets/70315473/3355cf19-d228-4650-81e9-8834cc953861)

**Comment by Nelfimov** [comment]
> поиск, тот что на скриншоте, я делаю по `всем гитхабовским профилям`, верно (глобальный поиск)?

Да

Только учтите что у гитхаба есть ограничение по graphql

**Comment by effektivnayarabota1** [comment]
@Nelfimov подскажи пожалуйста как лучше работу с `куки` **на клиенте организовать**, придумал 3 варианта:
1. разбирать строку, которую получаем c `document.cookie` при помощи `js'а`
2. подключить библиотеку для работы с куки на клиенте, [например вот эту](https://www.npmjs.com/package/react-cookie)
3. т.к. у нас куки назначаются только на сервере, можно в пропсах или через контекст передвавать с самой первой серверной функцией - `root layout server` - там же, где данные `вьювера` с сервера возвращаем

**Comment by Nelfimov** [comment]
@effektivnayarabota1 если выбирать между библиотекой и нативом, я предпочитаю натив пока это не усложнит мне жизнь. То есть зависит от объёма дополнительного кода. 

Третий вариант у тебя не понял о чем. 

+ @aliceinapple присоединяйся к беседе

**Comment by effektivnayarabota1** [comment]
> * удаление сотрудника из организации

- меняю `graphQl` запрос на `Rest`, не нашел ендпоинт
- ошибка при запросе. разбираюсь
```json
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/orgs/members#remove-an-organization-member",
  "status": "404"
}
```

**Comment by effektivnayarabota1** [comment]
### @aliceinapple help

нужно вывести ошибки на клиент. у нас есть [`такой компонент`](https://github.com/atls/team-management/tree/draft-error-client/ui/error-message/src), хочу вызывать его при помощи контекста в разных фрагментах. например [тут](https://github.com/atls/team-management/tree/draft-error-client/app/fragments/app-add-member-to-organization-modal) и [тут](https://github.com/atls/team-management/tree/draft-error-client/app/fragments/app-users-modal)
![image](https://github.com/user-attachments/assets/7dda8e10-72b3-4aba-adef-80b21fd1acce)

подключаю `контекст` в обоих фрагментах идентично, и [`вложенность`](https://github.com/atls/team-management/blob/draft-error-client/app/fragments/app-organization-card/src/organization-card.component.tsx) у них одинаковая
```ts
  const errorMessageDispatch = useContext(ErrorMessageDispatchContext)
  console.log('dispatch on users modal: ')
  console.log(errorMessageDispatch)
```
при этом, в логе на клиенте, один из фрагментов возвращает `null`, второй работает корректно

![image](https://github.com/user-attachments/assets/56aa6064-fcf9-4267-88fb-4b1f0e80be17)

не могу понять, почему так происходит

**Comment by aliceinapple** [comment]
@effektivnayarabota1 

Тут вроде было сообщение
Разобрался?

**Comment by effektivnayarabota1** [comment]
> @effektivnayarabota1
> 
> Тут вроде было сообщение Разобрался?

вообще да, было. 

вывожу ошибки на `клиент`, делал через `контекст` и `редьюсер`. в одном из компонентов `useContext` возвращает `null`, вместо `функции редьюсера`, спрашивал об этом.

нашел сторонний пакет с таким функционалом и лаконичным интерфейсом, буду менять эту громадину на него

**Comment by Nelfimov** [comment]
@effektivnayarabota1 какой статус?

**Comment by effektivnayarabota1** [comment]
> @effektivnayarabota1 какой статус?

вчера закончил, ревью запросил
