### ISSUE TITLE
модальное окно - приглашение участника команды

### ISSUE THREAD

**Issue by effektivnayarabota1** [atls/team-management#39]
### С чем связан запрос на фичу?

компонент находится в `базовом лэйауте`, используется на обеих страницах

### Расскажите как вы это себе видите

![image](https://github.com/atls/team-management/assets/70315473/c8bf679e-f5d8-4fce-bae5-1a17d8f3f9a4)

### Definition of done (критерий готовности)

копонент работает согласно дизайну

**Comment by effektivnayarabota1** [comment]
@Nelfimov подскажи пожалуйста:
1. какой инструмент использовать для работы с почтой
2. уточняю: 
    - приглашение в гитхаб организацию делается через `АПИ ГИТХАБА`, функционал приглашения через ссылку не нашел.
        - соответсвенно для того, чтобы выслать на почту приглашение мы установим `ORGANIZATION-NAME` в `переменную окружения`
    - `url-инвайты` на фигму дискорд и телеграм мы добавляем в переменные окружения (+ имя организации для запроса)
    - все 4 переменные делать обязательными или нет?

**Comment by Nelfimov** [comment]
> 1. какой инструмент использовать для работы с почтой

https://nodemailer.com

> 2. уточняю:
>    
>    * приглашение в гитхаб организацию делается через `АПИ ГИТХАБА`, функционал приглашения через ссылку не нашел.

Нам разве нужно везде высылать ссылку для инвайта отдельным письмом? Не вижу этого в дизайне.

Соответственно как я это представляю:
- где возможно: отправляем приглашение посредством апи (гитхаб)
- в остальных случаях: отправляем письмо на указанную почту с ссылками инвайтами

> * все 4 переменные делать обязательными или нет?

Конечно, иначе у тебя не будет работать сервис.

**Comment by effektivnayarabota1** [comment]
@Nelfimov подскажи пожалуйста
использую свой хук `useToast`, возвращает такую ошибку:
в текущем варианте `toastNotificationDispatch` - `nulll`

компонент вложен верно, находится внутри `toast provider`

такие ошибки у меня уже были, я так и не понял как они решались. я перебирал `package json`, она уходила
сейчас добавлял в `peer deps`, чистил кэш - не помогло

![image](https://github.com/user-attachments/assets/bd8a259d-e703-49ed-95d2-d4efbbee5ca6)

**Comment by effektivnayarabota1** [comment]
# UPD: решил
добавил   `"private": true`, в `@store/toast...`, проблема ушла. 
выглдят это очень странно, каждый раз какойто финт с `package.json` нужно сделать и каждый раз чтото новенькое

---

> 1. Вероятно где то не пробросил `peerDeps` для этого контекста

везде, где используется `@store/toast...`, этот пакет должнен быть подключен в том числе через `peerDeps`, верно?

**Comment by Nelfimov** [comment]
> # UPD: решил
> добавил `"private": true`, в `@store/toast...`, проблема ушла. выглдят это очень странно, каждый раз какойто финт с `package.json` нужно сделать и каждый раз чтото новенькое

Очень странное решение

> > 1. Вероятно где то не пробросил `peerDeps` для этого контекста
> 
> везде, где используется `@store/toast...`, этот пакет должнен быть подключен в том числе через `peerDeps`, верно?

Да - это очень частая проблема во фронтовой монорепе. Поэтому важно бросать и отображать ошибку если где то контекст не найдет.

**Comment by effektivnayarabota1** [comment]
@Nelfimov письмо же нужно `сверстать`, все верно? я запрос Илье отправил
[MJML](https://documentation.mjml.io/#inside-node-js) используем для верстки?

**Comment by effektivnayarabota1** [comment]
@Nelfimov уточняю:

cейчас в документации обнаружил интерфейсы для других почтовых протоколов. мы используем стандартный (`SMTP`) или какойто другой?
![image](https://github.com/user-attachments/assets/86e8c826-c0df-43ac-bce5-23d00bf9689e)

**Comment by Nelfimov** [comment]
> @Nelfimov уточняю:
> 
> cейчас в документации обнаружил интерфейсы для других почтовых протоколов. мы используем стандартный (`SMTP`) или какойто другой? ![image](https://private-user-images.githubusercontent.com/70315473/351806156-86e8c826-c0df-43ac-bce5-23d00bf9689e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDg1NzksIm5iZiI6MTcyMTg0ODI3OSwicGF0aCI6Ii83MDMxNTQ3My8zNTE4MDYxNTYtODZlOGM4MjYtYzBkZi00M2FjLWJjZTUtMjNkMDBiZjk2ODllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE5MTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZGQxMjYyMTZkN2I3NTkxMDZmNDQ5ZmVlNGViZWU1NjlhN2NhZjhmZmZkNTM2OGU5NDQ3NDJiYjM1MjUwZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4piKbAn1lWINbTtEGHaiumLCR2i-njzQZlnfW-bgCvY)

Стандартный

**Comment by Nelfimov** [comment]
> @Nelfimov письмо же нужно `сверстать`, все верно? я запрос Илье отправил [MJML](https://documentation.mjml.io/#inside-node-js) используем для верстки?

Можешь его. Можешь посмотреть в сторону других шаблонов. Можешь спросить в чате у @Amiditin каким он пользовался.

**Comment by Amiditin** [comment]
> Можешь спросить в чате у @Amiditin каким он пользовался.

Думаю, лучше использовать mjml. Сам пользовался обычным html + [handlebars](https://handlebarsjs.com/)
